Comport:
  port:                       "/dev/ttyACM0"
  baudrate:                   115200
  warmup:                     2.0

Experimental:
  mean-component-length:      10
  range-component-length:     5
  interval-between-component: 10.
  speaker:                    6
  reward-duration:            0.015
  number-of-rewards:          150
  inter-reward-interval:      3.
  range-IRI:                  1.
  light-pin:                  [4, 5, 7, 8]
  reward-pin:                 [2, 3]
  response-pin:               [-9, -10]
  postpone:                   2.

Metadata:
  subject:                    "enter-subject-name"
  condition:                  "2nd-step-of-training"

PinMode:
  10:                         "SSINPUT"
  9:                          "SSINPUT"
  8:                          "OUTPUT"
  7:                          "OUTPUT"
  6:                          "OUTPUT"
  5:                          "OUTPUT"
  4:                          "OUTPUT"
  3:                          "OUTPUT"
  2:                          "OUTPUT"
