Comport:
  port:                    "/dev/ttyACM0"
  baudrate:                115200
  warmup:                  2.0

Experimental:
  light-duration:          1.
  sound-duration:          1.
  speaker:                 6
  reward-duration:         0.015
  number-of-trial:         150
  inter-stimulus-interval: 3.
  interval-range:          1.
  light-pin:               [4, 5, 6, 7, 8]
  reward-pin:              [2, 3]
  response-pin:            [-9, -10]
  postpone:                .5

Metadata:
  subject:                 "enter-subject-name"
  condition:               "4th-step-of-training"

PinMode:
  10:                      "SSINPUT"
  9:                       "SSINPUT"
  8:                       "OUTPUT"
  7:                       "OUTPUT"
  6:                       "OUTPUT"
  5:                       "OUTPUT"
  4:                       "OUTPUT"
  3:                       "OUTPUT"
  2:                       "OUTPUT"
