Comport:
  port:                       "/dev/ttyACM0"
  baudrate:                   115200
  warmup:                     2.0

Experimental:
  light-pin:                  [4, 5, 6, 7, 8]
  reward-pin:                 [2, 3]
  speaker:                    6
  cue-duration:               1.5
  reward-duration:            0.02
  inter-stimulus-interval:    13.5
  isi-range:                  5.
  number-of-rewards:          200

Metadata:
  subject:                    "enter-subject-name"
  condition:                  "pavlovian-conditioning"

PinMode:
  10:                         "SSINPUT"
  9:                          "SSINPUT"
  8:                          "OUTPUT"
  7:                          "OUTPUT"
  6:                          "OUTPUT"
  5:                          "OUTPUT"
  4:                          "OUTPUT"
  3:                          "OUTPUT"
  2:                          "OUTPUT"
