Comport:
  port:                    "/dev/ttyACM0"
  baudrate:                115200
  warmup:                  2.0

Experimental:
  light-duration:          1.
  sound-duration:          1.
  speaker:                 6
  reward-duration:         0.02
  number-of-trial:         150
  lick:                    7
  inter-stimulus-interval: 19.
  light-pin:               [8, 9, 10, 11, 12]
  reward-pin:              [6, 7]
  lick-pin:                [4, 5]

Metadata:
  subject:                 "WT01R"
  condition:               "training-light"

PinMode:
  12:                      "OUTPUT"
  11:                      "OUTPUT"
  10:                      "OUTPUT"
  9:                       "OUTPUT"
  8:                       "OUTPUT"
  7:                       "OUTPUT"
  6:                       "OUTPUT"
  5:                       "SSINPUT"
  4:                       "SSINPUT"
